P. Wouters sugggested to remove or comment out this line
tcp10000check() causes trouble when running "ipsec verify" as in:

  File "/usr/local/libexec/ipsec/verify", line 119, in plutocheck
    tcp10000check()
NameError: global name 'tcp10000check' is not defined