kernel: apply fixes to when nft is enabled.
/source/rpmbuild/BUILD/libreswan-4.9_1226_gd2e4c04454ed_main/programs/pluto/kernel_policy.c:531:33: error: 'st' undeclared (first use in this function)
  531 |                                 st->st_logger,
      |                                 ^~
/source/rpmbuild/BUILD/libreswan-4.9_1226_gd2e4c04454ed_main/programs/pluto/kernel_policy.c:531:33: note: each undeclared identifier is reported only once for each function it appears in
/source/rpmbuild/BUILD/libreswan-4.9_1226_gd2e4c04454ed_main/programs/pluto/kernel_policy.c:532:33: error: passing argument 13 of 'raw_policy' from incompatible pointer type [-Werror=incompatible-pointer-types]
  532 |                                 "%s() add inbound Child SA", __func__)) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 1ff03847f4e0 ("kernel: move install_{{inbound,outbound}_ipsec,bare}_kernel_policy() code to kernel_policy.[hc]")