pluto: move defination to avoid unused USE_SECCOMP=false
/home/build/libreswan/programs/pluto/pluto_crypt.c:369:16: error: unused variable ‘logger’ [-Werror=unused-variable]
  369 |  struct logger logger[1] = { GLOBAL_LOGGER(null_fd), };