pluto: Fix potential operator precedence problem
Clang complains here because the ternary :? operator has lower
precedence than the bitwise or:

programs/pluto/connections.c:4094:39: error: operator '?:' has lower precedence than '|'; '|' will be evaluated first [-Werror,-Wbitwise-conditional-parentheses]
                        c->spd.that.key_from_DNS_on_demand ? "; " : "",
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
programs/pluto/connections.c:4094:39: note: place parentheses around the '|' expression to silence this warning
                        c->spd.that.key_from_DNS_on_demand ? "; " : "",
                                                           ^
                                                          )
programs/pluto/connections.c:4094:39: note: place parentheses around the '?:' expression to evaluate it first
                        c->spd.that.key_from_DNS_on_demand ? "; " : "",
                                                           ^
                        (                                             )