testing: switch argument order of check_jambuf()
The argument order in combination with how va_start was used on them
causes clang to print an error:

testing/check/jambuf/jambufcheck.c:85:16: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
                va_start(ap, ok);
                             ^
testing/check/jambuf/jambufcheck.c:26:51: note: parameter of type 'bool' is declared here
static void check_jambuf(const char *expect, bool ok, ...)
                                                  ^