Fix compilation error on Fedora 44
On Fedora 44, where -Wunused-but-set-variable is enabled with GCC 16,
the build fails with:

  ikev2_proposals.c: In function ‘process_transforms’:
  ikev2_proposals.c:453:46: error: variable ‘local_proposal’ set but not used [-Werror=unused-but-set-variable=]
    453 |                 const struct ikev2_proposal *local_proposal;
        |                                              ^~~~~~~~~~~~~~
  ikev2_proposals.c:773:32: error: variable ‘local_proposal’ set but not used [-Werror=unused-but-set-variable=]
    773 |         struct ikev2_proposal *local_proposal;
        |                                ^~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

This fixes it by adding the UNUSED attribute to the local variable.

Signed-off-by: Daiki Ueno <dueno@redhat.com>