pluto: Add missing assignment operators
Omitting the assignment operator is a GNU extension which clang does not
support:

programs/pluto/state.c:116:21: error: use of GNU 'missing =' extension in designator [-Werror,-Wgnu-designator]
        [STATE_IKEv1_ROOF] &state_ikev1_roof,
                           ^
                           =