testing: travis f3 install only x86_64 dependencies
Error: Transaction check error:
  file /usr/bin/bashbug from install of bash-5.0.7-1.fc30.i686 conflicts with file from package bash-5.0.7-1.fc30.x86_64