logging: for tools, add ERROR et.al. after program name
for instance:
   ipsec whack: FATAL ERROR: no such process
rather than:
   FATAL ERROR: ipsec whack: no such process
will need to mass update tests

Note: this doesn't apply to pluto, it always prints:
   ERROR: <prefix>: ...
which currently results in:
   ERROR: ipsec pluto: ...
later, much later