testing: drop machine=... in machine xml files
Suspect it is causing:

  error: Failed to start domain w5.nic
  error: internal error: process exited while connecting to monitor: 2020-09-21T22:52:01.064369Z qemu-system-x86_64: -machine accel=kvm: unsupported machine type

on the testing machines.

So far tested on F32.

Follow-up 43da4a5cda74cb4c0c853d8439cd7af29cff17f0