Add printf format attributes to printf-like functions
This solves a problem when compiling with clang:

lib/libswan/jambuf.c:186:39: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
        int sn = vsnprintf(d.cursor, d.size, format, ap);
                                             ^~~~~~

And should also result in better error reporting since the compiler
knows about the parameter of the surrounding function being a printf
format string.