selinux: support dynamic class/perm discovery
The older API has been deprecated which breaks Werror builds.

  In file included from /home/lkundrak/fedora/libreswan/libreswan-3.15/programs/pluto/security_selinux.h:19:0,
                   from /home/lkundrak/fedora/libreswan/libreswan-3.15/programs/pluto/ikev1_spdb_struct.c:61:
   #warning "Please remove any #include's of this header in your source code."
   #warning "Instead, use string_to_security_class() to map the class name to a value."

  In file included from /home/lkundrak/fedora/libreswan/libreswan-3.15/programs/pluto/security_selinux.h:20:0,
                   from /home/lkundrak/fedora/libreswan/libreswan-3.15/programs/pluto/plutomain.c:103:
  /usr/include/selinux/av_permissions.h:1:2: error: #warning "Please remove any #include of this header in your source code." [-Werror=cpp]
   #warning "Please remove any #include of this header in your source code."
   #warning "Instead, use string_to_av_perm() to map the permission name to a value."
    ^
  cc1: all warnings being treated as errors