constants: fix build with gcc6
  lib/libswan/constants.c:1069:19: error: 'modecfg_attr_names_draft'
   defined but not used [-Werror=unused-const-variable=]
   static enum_names modecfg_attr_names_draft = {
                     ^~~~~~~~~~~~~~~~~~~~~~~~

  lib/libswan/constants.c:857:26: error: 'ipsec_var_attr_name'
   defined but not used [-Werror=unused-const-variable=]
   static const char *const ipsec_var_attr_name[] = {
                            ^~~~~~~~~~~~~~~~~~~

  programs/pluto/kernel_netlink.c:80:38: error: 'broad_proto_info'
   defined but not used [-Werror=unused-const-variable=]
   static const struct pfkey_proto_info broad_proto_info[2] = {
                                        ^~~~~~~~~~~~~~~~

  programs/pluto/pluto_constants.c:222:26: error: 'natt_method_result_name'
  defined but not used [-Werror=unused-const-variable=]
   static const char *const natt_method_result_name[] = {
                            ^~~~~~~~~~~~~~~~~~~~~~~

  cc1: all warnings being treated as errors