building: linux building  HAVE_NFTABLES=true
6897745f20b7 ("building: set HAVE_IPTABLES?=true in linux.mk")
broke building with

HAVE_NFTABLES=true make base

../../include/ipsecconf/keywords.h:445:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before string constant
  445 | error "set HAVE_IPTABLES or HAVE_NFTABLES"

either set HAVE_NFTABLES or HAVE_IPTABLES not both.