ikev2 proposals: add support for multiple key exchanges
the syntax is
  <encr>-<prf>-<DH>-<addke1>-<addke2>- ... -<addke7>.

Signed-off-by: Daiki Ueno <ueno@gnu.org>

--- MAIN/testing/pluto/algparse-01/west.console.txt
+++ OUTPUT/testing/pluto/algparse-01/west.console.txt
@@ -1570,9 +1570,9 @@
 algparse -v2 'ike=aes_gcm-none;modp2048' (expect SUCCESS)
 	AES_GCM_16-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048
 algparse -v2 'ike=aes_gcm-sha1-none-modp2048' (expect ERROR)
-	ERROR: IKE proposal contains unexpected 'modp2048'
+	ERROR: IKE DH algorithm 'none' not permitted
 algparse -v2 'ike=aes_gcm-sha1-none;modp2048' (expect ERROR)
-	ERROR: IKE proposal contains unexpected 'modp2048'
+	ERROR: IKE DH algorithm 'none' not permitted
 algparse -v2 'ike=aes+aes_gcm' (expect ERROR)
 	ERROR: AEAD and non-AEAD IKE encryption algorithm cannot be combined
 algparse -v2 'ike=,' (expect ERROR)

algparse -v2 'ike=aes_cbc-sha1-modp2048-modp2048'
	AES_CBC-HMAC_SHA1-MODP2048