pluto: add extra enum for xfrmi interface to compile on CentOS 6,7,8
Add missing enum declerations to compile xfrmi support on older
distributions, with older if_link.h.

use
make USE_XFRM_INTERFACE_IFLA_HEADER=true programs

error when USE_XFRM_INTERFACE_IFLA_HEADER=false with older
kernel headers < 4.19
Compile error:
/root/rpmbuild/BUILD/libreswan-3.28rc1494_g7c7a490_xfrmi/programs/pluto/kernel_xfrm_interface.c:180:30: error:
'IFLA_XFRM_IF_ID' undeclared (first use in this function)
  nl_addattr32(&req->n, 1024, IFLA_XFRM_IF_ID, if_id);

"ipsec-interface=yes" need kernel 4.19 or xfrmi back ported.
If kernel is missing xfrmi, e.g on kernel-2.6.32-696.16.1.el6.x86_64 on CentOS 6,
the connection will fail to load.

036 ipsec-interface=1 not supported. may be missing CONFIG_XFRM_INTERFACE support in kernel

Tested by Paul on CentOS 6 and Tuomo on Foo Linux 7.