libswan: suppress unused when USE_DNSSEC=false
brutely suppress warning:
lib/libswan/addr_lookup.c:197:24: error: unused parameter ‘logger’ [-Werror=unused-parameter]
  197 |         struct logger *logger)
      |         ~~~~~~~~~~~~~~~^~~~~~