testing: fix nusrn change in shell.Remote
change due to broke nsrun
 1fd5be97047a ("Revert "Revert "kvm: switch to pexpect.spawn(command, args[])""")

build@swantest:~/libreswan/testing/pluto/ikev2-11-simple-psk (main)$ ../../utils/nsrun --ns
prefix [] 0
nsrunner 0.00: Options:
nsrunner 0.00:   directories: ['/home/build/libreswan/testing/pluto/']
nsrunner 0.00:   verbose: info
nsrunner 0.00: ipsec version
nsrunner 0.00: ***** NS PLUTO RUNNING TEST ikev2-11-simple-psk *******
Traceback (most recent call last):
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 4395, in <module>
    main()
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 4318, in main
    test = setup_single_test(args, cwd)
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 3197, in setup_single_test
    do_single_test(args=args, test=test)
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 3238, in do_single_test
    if test.do_test():
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 3816, in do_test
    self.sudo = localhost_sudo(self.args, self.name)
  File "/home/build/libreswan/testing/pluto/ikev2-11-simple-psk/../../utils/nsrun", line 3112, in localhost_sudo
    s = shell.Remote(cmd, logger, hostname=args.node, username="root")
  File "/home/build/libreswan/testing/utils/fab/shell.py", line 165, in __init__
    self.child = pexpect.spawn(command[0], args=command[1:], timeout=0)
  File "/usr/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 263, in _spawn
    raise TypeError('The argument, args, must be a list.')
TypeError: The argument, args, must be a list.