pluto: fix a typo
Caught by gcc6:

  programs/pluto/packet.c:952:19: error: 'ikev2_cert_req_fields'
  defined but not used [-Werror=unused-const-variable=]
   static field_desc ikev2_cert_req_fields[] = {
                     ^~~~~~~~~~~~~~~~~~~~~

No real problem since the structures are essentially the same.