testing: expect more detailed Pluto not running message from whack
i.e., identical to addconn:
  ERROR: ipsec whack: Pluto is not running (no "/run/pluto/pluto.ctl"): No such file or directory (errno 2)
(perhaps too detailed)