Revert "pluto: only set replay-window on the inbound IPsec SA"
This reverts commit 8116a49394886f306dee7572bbb87d6fe0a7b223.

It gets the error:
  ERROR: "westnet-eastnet-ikev2" #2: netlink response for Add SA esp.ea625bf@192.1.2.45: Invalid argument (errno 22)
when installing the outbound SA on east and then that cascades
leading to if(debug)passert().

See #1507 and #1508