addcon: include lswlog.h
92ceb628b was a bit aggressive.
addcon fails to compile with USE_SECCOMP=false

/home/build/libreswan/programs/addconn/addconn.c:538:20: error: 'RC_UNKNOWN_NAME' undeclared (first use in this function); did you mean 'AI_CANONNAME'?
     exit_status += RC_UNKNOWN_NAME; /* cause non-zero exit code */