building: move the check outside ifdef
Fixes: 231feaf8faafc ("FRM: Add ipsec0 support by mapping it onto if_d 16384")
leave it outside the ifdef otherwise

home/a/libreswan/programs/pluto/kernel_xfrm.c:516:19: error: unused parameter ‘xfrm_if_id’ [-Werror=unused-parameter]
    const uint32_t xfrm_if_id,
                   ^~~~~~~~~~
cc1: all warnings being treated as errors
../../mk/depend.mk:32: recipe for target 'kernel_xfrm.o' failed
-               if (xfrm_if_id > 0) {
 #ifdef USE_XFRM_INTERFACE
+               if (xfrm_if_id != 0) {